targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: en
          input_directory: assets/i18n
          input_file_pattern: .json
          output_directory: lib/i18n
          locale_handling: true
          deferred_loading: false
